### ISSUE TITLE
No one seems to have your email..

### ISSUE THREAD

**Issue by BobbysGithub** [keklikyusuf/DeltaElektronika#4]
Could you contact me?
I'm tracking down a crc issue with the modbus interface.
If you have time/desire to help....

**Comment by keklikyusuf** [comment]
Of course, I will take a flight now but if you can send me the broken code part and error message I can try it when I reach to a place an internet 😊

**Comment by BobbysGithub** [comment]
Hello mister,

hope you are having a good time, no broken bones and stuf.

The crc issue is fixed i think. the issue was that the code would remove
0's. 0abc would become bca after the byte swap.

i think this is also why we had that thing that fuse limit 10 would not
work but 11 would.

Worked on the 1250 mbus lib for Nikos lastweek. Man does that thing have
allot of indexes!
also made a lib for the datalogger. read voltage and temp, we dont use much
more than that :p.

Cmr firmwar version is 60.21 and counting. Voltronic's been buzzy.

Have fun!

Op ma 17 jan. 2022 14:57 schreef Yusuf Keklik ***@***.***>:
