### ISSUE TITLE
could this work for delta electronika sm330-ar-22?

### ISSUE THREAD

**Issue by Andrea1996M** [keklikyusuf/DeltaElektronika#5]

**Comment by keklikyusuf** [comment]
Comments that are available on both power supplies should work together.
https://www.delta-elektronika.nl/products/sm3300-series
Here is the datasheet of the SM330-AR-22 and available comments can be compared to see common comments. 
I just did a quick check for you for voltage measurements as an example, "MEASure:VOLtage?<term>" , it is same for both power supplies so SM15K package can be used for SM330-AR-22 as well on this comment.
